### PR TITLE
update weights

### PR DESCRIPTION
**Pull request by coderobe**
weights from the 0.9.27 release benchmarks 🏋️‍♀️

Backport to master: https://github.com/paritytech/polkadot/pull/5844

cumulus companion branch: test-release-v0.9.27

### CODE REVIEW

File: runtime/kusama/src/weights/pallet_scheduler.rs [hunk 1]
```diff
@@ -77,9 +77,9 @@ impl<T: frame_system::Config> pallet_scheduler::WeightInfo for WeightInfo<T> {
 	// Storage: Preimage StatusFor (r:1 w:1)
 	/// The range of component `s` is `[1, 50]`.
 	fn on_initialize_periodic_resolved(s: u32, ) -> Weight {
-		(0 as Weight)
-			// Standard Error: 36_000
-			.saturating_add((24_281_000 as Weight).saturating_mul(s as Weight))
+		(908_000 as Weight)
```
Comment (chevdor) [inline runtime/kusama/src/weights/pallet_scheduler.rs:80]: 0 to 900k

File: runtime/polkadot/src/weights/pallet_scheduler.rs [hunk 2]
```diff
@@ -77,9 +77,9 @@ impl<T: frame_system::Config> pallet_scheduler::WeightInfo for WeightInfo<T> {
 	// Storage: Preimage StatusFor (r:1 w:1)
 	/// The range of component `s` is `[1, 50]`.
 	fn on_initialize_periodic_resolved(s: u32, ) -> Weight {
-		(1_851_000 as Weight)
-			// Standard Error: 29_000
-			.saturating_add((23_826_000 as Weight).saturating_mul(s as Weight))
+		(0 as Weight)
```
Comment (chevdor) [inline runtime/polkadot/src/weights/pallet_scheduler.rs:80]: down to 0

**Review by chevdor — APPROVED** [review]
The new weights are very constistant with the previous `0.9.26-1` release.

**Review by ggwpez — APPROVED** [review]
Link to [SWC](https://weights.tasty.limo:8443/compare?unit=weight&ignore_errors=true&threshold=10&method=guess-worst&repo=polkadot&old=release-v0.9.27&new=coderobe/weights-27&path_pattern=runtime/**/src/weights/**/*.rs) staging (since Im testing some stuff).  
Extrinsic and Block weights look good.

**Comment by coderobe** [comment]
error[E0046]: not all trait items implemented, missing: `remove_member_wrong_refund`
    --> /builds/parity/mirrors/polkadot/runtime/kusama/src/weights/pallet_elections_phragmen.rs:46:1
     |
  46 | impl<T: frame_system::Config> pallet_elections_phragmen::WeightInfo for WeightInfo<T> {
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `remove_member_wrong_refund` in implementation
     |
     = help: implement the missing item: `fn remove_member_wrong_refund() -> u64 { todo!() }`

File: runtime/kusama/src/weights/pallet_elections_phragmen.rs [hunk 3]
```diff
@@ -116,75 +116,67 @@ impl<T: frame_system::Config> pallet_elections_phragmen::WeightInfo for WeightIn
...
 	// Storage: Council Proposals (r:1 w:0)
 	// Storage: Council Members (r:0 w:1)
 	fn remove_member_with_replacement() -> Weight {
-		(61_276_000 as Weight)
+		(61_875_000 as Weight)
 			.saturating_add(T::DbWeight::get().reads(5 as Weight))
 			.saturating_add(T::DbWeight::get().writes(5 as Weight))
 	}
-	// Storage: PhragmenElection RunnersUp (r:1 w:0)
-	fn remove_member_wrong_refund() -> Weight {
```
Comment (coderobe) [inline runtime/kusama/src/weights/pallet_elections_phragmen.rs:145]: huh, this got dropped, breaking the build. i'll undo this change

Comment (ggwpez) [reply runtime/kusama/src/weights/pallet_elections_phragmen.rs:145]: Yep not your fault, caused by https://github.com/paritytech/substrate/pull/11790 which removed the benchmark but did not update the weight-trait.

Comment (coderobe) [reply runtime/kusama/src/weights/pallet_elections_phragmen.rs:145]: @ggwpez should i merge your pr into this branch to fix it rather than readding the old weight?

Comment (ggwpez) [reply runtime/kusama/src/weights/pallet_elections_phragmen.rs:145]: It would be probably slightly cleaner to remove it from the trait as in my MR for Polkadot and Kusama.  
This only makes a difference if someone re-benchmarks on this branch.

**Comment by coderobe** [comment]
test failures:
---- test_fees::full_block_council_election_cost stdout ----
can support 6748 voters in a single block for council elections; total bond 138846
thread 'test_fees::full_block_council_election_cost' panicked at 'assertion failed: cost_dollars > 150_000', runtime/polkadot/src/lib.rs:2128:9

**Comment by coderobe** [comment]
this is the one we already fixed last time, isn't it

**Comment by coderobe** [comment]
test-linux-stable has some unrelated nonfatal errors in the test execution:
```
Error: 
   0: Other: can only use subcommand with --chain [polkadot-dev, kusama-dev, westend-dev, rococo-dev, wococo-dev], got ksmcc3
  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                                ⋮ 5 frames hidden ⋮                               
   6: <core::result::Result<T,F> as core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible,E>>>::from_residual::hb6013e93a45d6539
      at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/result.rs:2105
   7: polkadot::main::h147a60bb32358d3d
      at /builds/parity/mirrors/polkadot/src/main.rs:25
   8: core::ops::function::FnOnce::call_once::hf3c5751998646e70
      at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/ops/function.rs:248
                                ⋮ 14 frames hidden ⋮     
```

This is not our fault though and should probably be fixed by whoever maintains the test ci

**Comment by coderobe** [comment]
also `Aug 01 11:54:47.708 ERROR runtime::inclusion-inherent: BUG: disputed_bitfield != expected_bits` and a handful of other various things

**Comment by coderobe** [comment]
bot merge

**Comment by chevdor** [comment]
bot merge
