### PR TITLE
Changes for substrate#3821

### PR DESCRIPTION
**Pull request by expenses**
https://github.com/paritytech/substrate/pull/3821 added a `Debug` derive to rstd, which we can use instead of ` #[cfg_attr(feature = "std", derive(Encode))]`. It also broke some other stuff to do with `Debug`:
```
error[E0277]: `registrar::LimitParathreadCommits<T>` doesn't implement `core::fmt::Debug`
   --> /Users/ashley/projects/polkadot/runtime/src/registrar.rs:505:30
    |
505 | impl<T: Trait + Send + Sync> SignedExtension for LimitParathreadCommits<T> where
    |                              ^^^^^^^^^^^^^^^ `registrar::LimitParathreadCommits<T>` cannot be formatted using `{:?}`
    |
    = help: the trait `core::fmt::Debug` is not implemented for `registrar::LimitParathreadCommits<T>`
    = note: add `#[derive(Debug)]` or manually implement `core::fmt::Debug`
```

This should only get merged once `polkadot-master` gets updated and the branch changes from `polkadot-master` to `master` have been reverted.

### CODE REVIEW

**Comment by andresilva** [comment]
Sorry but I was already working on this and didn't notice this PR. The proper solution is to use a derive introduced in https://github.com/paritytech/substrate/pull/3821/ called `RuntimeDebug`. I opened a PR that updates to latest `substrate-master` branch #491.
